name: "bert"
platform: "onnxruntime_onnx"
max_batch_size : 8
dynamic_batching {}

# If remove this, onnx runtime will be used.
optimization { execution_accelerators {
  gpu_execution_accelerator : [ {
    name : "tensorrt"
    parameters { key: "precision_mode" value: "FP16" }
    parameters { key: "max_workspace_size_bytes" value: "1073741824" }
    }]
}}